build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 12
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 30

exceptions:
  TooGenericExceptionCaught:
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable

naming:
  MatchingDeclarationName:
    active: false
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  ReturnCount:
    max: 5
